### ISSUE TITLE
Schoology plus 

### ISSUE THREAD

**Issue by vcannon2** [jsadowyj0/schoology-ext#10]
I just found this extension and I was hoping it would work but I think I ran into a problem.
so I added the extension to my browser and tried to use it with schoology plus which is another Schoology extension so I was just wondering if you could check that out.

**Comment by Orion31Dev** [comment]
Hi, this is probably an issue with the manifest rather than Schoology Plus. Chrome extensions are required to list each website that they should run on, and schools tend to run Schoology on their own website, so we need to list each school website. Please tell me your school's Schoology website so I can add it to the manifest.

**Comment by vcannon2** [comment]
the link to the sign-in page is lms.lausd.net

**Comment by Orion31Dev** [comment]
What is the link to the schoology home page?

**Comment by vcannon2** [comment]
[here](https://lms.lausd.net/#/?_k=r7wa21) it is

**Comment by Orion31Dev** [comment]
I get instantly redirected when I click the link, so I need your help to find out the url of the home page, the assignment page, and the calendar page. For me, the assignment page is `schoology.[school].com/assignment`, but your school is set up with Microsoft, not GSuite, so I'm not sure.

**Comment by vcannon2** [comment]
[calendar](https://lms.lausd.net/calendar/66743385/2020-10)
for the assignment page do you mean the grade page or courses and folders?

**Comment by Orion31Dev** [comment]
the page where you can submit the assignment. I'm guessing it's /assignment/{id}

**Comment by vcannon2** [comment]
that's the thing there are a lot of assignments so would you need every single one because they are all different 
like https://lms.lausd.net/assignment/3226084740/info  but then there's another assignment with a different id 
       https://lms.lausd.net/assignment/3139542516/info

**Comment by Orion31Dev** [comment]
@vcannon2 it should work now, but @jsadowyj0 needs to update the Web Store listing, so for now just download the code from the `dev` branch and unzip. Then go to [chrome://extensions/](chrome://extensions/) and click "Load Unpacked" and select the folder.
