### ISSUE TITLE
Please add hcps.us to your list.

### ISSUE THREAD

**Issue by cpocai** [jsadowyj0/schoology-ext#2]
Having the same issue with the check marks as reported below. Thank you!

**Comment by jsadowyj0** [comment]
I am going to need the full domain that your school uses. Also, please just comment on the already existing issue so we don't have duplicate issues. Thanks!

**Comment by Orion31Dev** [comment]
@jsadowyj0 the domain is https://hcps.schoology.com/ I looked it up
